// amplify_outputs.json is generated by `npx ampx sandbox`.
// Declaring the module here prevents TS errors before the file exists.
declare module '@/amplify_outputs.json' {
  import type { ResourcesConfig } from 'aws-amplify'
  const config: ResourcesConfig
  export default config
}
