import 'react-native-get-random-values'
import 'react-native-url-polyfill/auto'
import { Amplify } from 'aws-amplify'

/**
 * Call configureAmplify() once at app startup (in app/_layout.tsx).
 *
 * amplify_outputs.json is generated by the backend sandbox:
 *   cd apps/web && npx ampx sandbox
 *
 * Then copy the generated file here:
 *   cp apps/web/amplify_outputs.json apps/mobile/amplify_outputs.json
 */
export function configureAmplify() {
  try {
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const config = require('../amplify_outputs.json')
    Amplify.configure(config)
  } catch {
    console.warn(
      '[Amplify] amplify_outputs.json not found.\n' +
        'Copy it from apps/web after running `npx ampx sandbox`.'
    )
  }
}
